# Cloudflare Pages Configuration
build:
  command: npm run build
  output: public
  environment:
    NODE_VERSION: 22.12.0
    NPM_VERSION: 10.8.2

# Functions configuration
functions:
  directory: functions
  compatibility_date: 2024-09-18
  compatibility_flags:
    - nodejs_compat

# Routes configuration
routes:
  - include: /api/*
  - include: /health
  - include: /*
  - exclude: /static/*
