name = "profiler-lead-recon"
main = "dist/api/simple-server.js"
compatibility_date = "2024-09-18"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "profiler-lead-recon-prod"
route = "profiler.leadrecon.app/*"

[env.production.vars]
NODE_ENV = "production"
GAMMA_ENABLED = "true"
DEFAULT_DECK_PROVIDER = "gamma"
ENABLE_MCP_RUBE = "true"

[[env.production.kv_namespaces]]
binding = "PROFILER_KV"
id = "profiler_kv_namespace"

[[env.production.r2_buckets]]
binding = "PROFILER_R2"
bucket_name = "profiler-assets"

[env.staging]
name = "profiler-lead-recon-staging"
route = "staging.profiler.leadrecon.app/*"

[env.development]
name = "profiler-lead-recon-dev"

[build]
command = "echo 'Build completed'"
cwd = "."

[triggers]
crons = ["0 0 * * 1"]
