name = "profiler-lead-recon"
compatibility_date = "2024-09-18"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

[env.production]
name = "profiler-lead-recon-prod"

[env.production.vars]
NODE_ENV = "production"
GAMMA_ENABLED = "true"
DEFAULT_DECK_PROVIDER = "gamma"
ENABLE_MCP_RUBE = "true"

[[env.production.kv_namespaces]]
binding = "PROFILER_KV"
id = "profiler_kv_namespace"

[[env.production.r2_buckets]]
binding = "PROFILER_R2"
bucket_name = "profiler-assets"

[env.staging]
name = "profiler-lead-recon-staging"

[env.development]
name = "profiler-lead-recon-dev"

[build]
command = "npm install && npm run build"
cwd = "."

[triggers]
crons = ["0 0 * * 1"]
